name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow  }}-${{ github.event.pull_request.number || github.ref  }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        go: [ '1.16', '1.17', '1.18', 'latest']
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: go version
        run: go version
      - name: Run Test
        run: go test --cover -v
